# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - func-net8-fvbp

on:
  push:
    branches:
      - net8.0-inproc
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: List Cloned Repo 1
        shell: pwsh
        run: ls

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          repository: sag-group/ACMESharpCore
          ssh-key: ${{ secrets.ACMESharpCore_DEPLOY_KEY }}
          path: "./ACMESharpCore"

      - name: List Cloned Repo 2
        shell: pwsh
        run: ls ./ACMESharpCore
        
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E25CB011CF3B4837B394D2EE90524A00 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E99796B70BF4AE0898DE6AEF704EE55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17F1F0775A624182B8E3E3BFE93195A4 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'func-net8-fvbp'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          